### ISSUE TITLE
flag overlapping text

### ISSUE THREAD

**Issue by danilocastelhano1** [MRameez820/Ion-select-with-image#1]
hi, in your prints, you flag when selected text is in the left and the text is next after the flag, how you did this? i saw you have a class in ion option called coin-opt, where is this class?

thanks

**Comment by MRameez820** [comment]
Sorry class coin-opt is not used in code I updated code...........check coin-select in home.page.scss padding left and right are responsible for its position

**Comment by danilocastelhano1** [comment]
Ohh i thought that, so my padding is like that:
![image](https://user-images.githubusercontent.com/52941839/98369525-da13cf00-2017-11eb-8601-553aa4c840ad.png)
i don't know what to do in this case, can you help me ?

**Comment by MRameez820** [comment]
by changing padding-left still its same ?

**Comment by danilocastelhano1** [comment]
fixed, i had another css with padding-left: 0 !important, sorry to disturb

**Comment by MRameez820** [comment]
No issue i am glad it's solved

**Comment by danilocastelhano1** [comment]
![image](https://user-images.githubusercontent.com/52941839/98372519-a4bdb000-201c-11eb-91eb-fe671b8b3f96.png)
The result, you're awesome, much thanks
